package sesion10;

public class FrmPresentación extends javax.swing.JFrame {

    public FrmPresentación() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField1 = new componentes.TextField();
        textField2 = new componentes.TextField();
        textField3 = new componentes.TextField();
        textField4 = new componentes.TextField();
        combobox2 = new componentes.Combobox();
        combobox1 = new componentes.Combobox();
        combobox3 = new componentes.Combobox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setBackground(new java.awt.Color(24, 24, 24));
        textField1.setFont(new java.awt.Font("Josefin Sans Light", 0, 16)); // NOI18N
        textField1.setLabelText("Nombres");
        textField1.setLineColor(new java.awt.Color(42, 143, 136));
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 93, 300, 40));

        textField2.setBackground(new java.awt.Color(24, 24, 24));
        textField2.setFont(new java.awt.Font("Josefin Sans Light", 0, 16)); // NOI18N
        textField2.setLabelText("Apellido Paterno");
        textField2.setLineColor(new java.awt.Color(42, 143, 136));
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 147, 300, 40));

        textField3.setBackground(new java.awt.Color(24, 24, 24));
        textField3.setFont(new java.awt.Font("Josefin Sans Light", 0, 16)); // NOI18N
        textField3.setLabelText("Nombres");
        textField3.setLineColor(new java.awt.Color(42, 143, 136));
        jPanel1.add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 255, 300, 40));

        textField4.setBackground(new java.awt.Color(24, 24, 24));
        textField4.setFont(new java.awt.Font("Josefin Sans Light", 0, 16)); // NOI18N
        textField4.setLabelText("Apellido Materno");
        textField4.setLineColor(new java.awt.Color(42, 143, 136));
        jPanel1.add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 201, 300, 40));

        combobox2.setBackground(new java.awt.Color(24, 24, 24));
        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero (a)", "Casado" }));
        combobox2.setFont(new java.awt.Font("Josefin Sans Light", 0, 16)); // NOI18N
        combobox2.setLabeText("");
        jPanel1.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 310, 300, 50));

        combobox1.setBackground(new java.awt.Color(24, 24, 24));
        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Viudo", "Divorciado" }));
        combobox1.setFont(new java.awt.Font("Josefin Sans", 0, 16)); // NOI18N
        combobox1.setLabeText("");
        jPanel1.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 290, -1));

        combobox3.setBackground(new java.awt.Color(24, 24, 24));
        combobox3.setForeground(new java.awt.Color(255, 255, 255));
        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        combobox3.setSelectedIndex(-1);
        jPanel1.add(combobox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPresentación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPresentación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPresentación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPresentación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPresentación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Combobox combobox1;
    private componentes.Combobox combobox2;
    private componentes.Combobox combobox3;
    private javax.swing.JPanel jPanel1;
    private componentes.TextField textField1;
    private componentes.TextField textField2;
    private componentes.TextField textField3;
    private componentes.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
